# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gtL_zcdwotMvBusJo11I3HNBoQxkT-K2
"""
import spaces

@spaces.GPU
def dummy_gpu_func():
    pass
import sqlite3
import json
import os
import gradio as gr
from huggingface_hub import InferenceClient

# --- 1. VERİTABANI KONTROLÜ VE OLUŞTURULMASI ---
def init_db():
    conn = sqlite3.connect('comic_store.db')
    cursor = conn.cursor()

    cursor.execute('''
        CREATE TABLE IF NOT EXISTS comics (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            title TEXT NOT NULL,
            publisher TEXT NOT NULL,
            price REAL NOT NULL,
            stock INTEGER NOT NULL
        )
    ''')

    cursor.execute('''
        CREATE TABLE IF NOT EXISTS orders (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            customer_name TEXT NOT NULL,
            comic_id INTEGER NOT NULL,
            quantity INTEGER NOT NULL,
            total_price REAL NOT NULL,
            status TEXT DEFAULT 'Hazırlanıyor',
            FOREIGN KEY (comic_id) REFERENCES comics (id)
        )
    ''')

    cursor.execute('SELECT COUNT(*) FROM comics')
    if cursor.fetchone()[0] == 0:
        sample_comics = [
            ('Spider-Man: Blue', 'Marvel', 150.0, 10),
            ('Batman: The Killing Joke', 'DC Comics', 180.0, 5),
            ('Watchmen', 'DC Comics', 320.0, 3),
            ('Saga Vol. 1', 'Image Comics', 140.0, 8),
            ('Sandman: Preludes & Nocturnes', 'Vertigo', 250.0, 4),
            ('Akira Vol. 1', 'Kodansha', 450.0, 0),  # Stokta yok testi için
            ('X-Men: Dark Phoenix Saga', 'Marvel', 210.0, 2),
            ('V for Vendetta', 'DC Comics', 290.0, 6)
        ]
        cursor.executemany('''
            INSERT INTO comics (title, publisher, price, stock)
            VALUES (?, ?, ?, ?)
        ''', sample_comics)

    conn.commit()
    conn.close()

# Veritabanını başlat
init_db()


# --- 2. MODEL TOOLS (ŞEMA TANIMLARI) ---
TOOLS_SCHEMA = [
    {
        "type": "function",
        "function": {
            "name": "get_comics_catalog",
            "description": "Mağazadaki tüm çizgi romanların listesini, fiyat ve stok bilgisiyle getirir.",
            "parameters": {"type": "object", "properties": {}, "required": []}
        }
    },
    {
        "type": "function",
        "function": {
            "name": "search_comic",
            "description": "Arama kelimesine göre çizgi roman arar.",
            "parameters": {
                "type": "object",
                "properties": {
                    "query": {"type": "string", "description": "Aranacak çizgi roman veya yayıncı adı"}
                },
                "required": ["query"]
            }
        }
    },
    {
        "type": "function",
        "function": {
            "name": "create_order",
            "description": "Seçilen çizgi roman için sipariş oluşturur ve stoğu günceller.",
            "parameters": {
                "type": "object",
                "properties": {
                    "comic_id": {"type": "integer", "description": "Çizgi romanın veritabanındaki ID'si"},
                    "quantity": {"type": "integer", "description": "Sipariş edilecek adet"},
                    "customer_name": {"type": "string", "description": "Müşterinin adı soyadı"}
                },
                "required": ["comic_id", "quantity", "customer_name"]
            }
        }
    }
]


# --- 3. VERİTABANI FONKSİYONLARI ---
def get_comics_catalog():
    conn = sqlite3.connect('comic_store.db')
    cursor = conn.cursor()
    cursor.execute('SELECT id, title, publisher, price, stock FROM comics')
    rows = cursor.fetchall()
    conn.close()

    catalog = []
    for r in rows:
        catalog.append({
            "id": r[0],
            "title": r[1],
            "publisher": r[2],
            "price": f"{r[3]} TL",
            "stock": r[4]
        })
    return json.dumps(catalog, ensure_ascii=False)

def search_comic(query: str):
    conn = sqlite3.connect('comic_store.db')
    cursor = conn.cursor()
    cursor.execute('SELECT id, title, publisher, price, stock FROM comics WHERE title LIKE ? OR publisher LIKE ?',
                   (f'%{query}%', f'%{query}%'))
    rows = cursor.fetchall()
    conn.close()

    results = []
    for r in rows:
        results.append({
            "id": r[0],
            "title": r[1],
            "publisher": r[2],
            "price": f"{r[3]} TL",
            "stock": r[4]
        })
    return json.dumps(results if results else {"message": "Aranan kriterde çizgi roman bulunamadı."}, ensure_ascii=False)

def create_order(comic_id: int, quantity: int, customer_name: str):
    conn = sqlite3.connect('comic_store.db')
    cursor = conn.cursor()

    cursor.execute('SELECT title, price, stock FROM comics WHERE id = ?', (comic_id,))
    comic = cursor.fetchone()

    if not comic:
        conn.close()
        return json.dumps({"error": "Geçersiz Çizgi Roman ID!"}, ensure_ascii=False)

    title, price, stock = comic

    if stock < quantity:
        conn.close()
        return json.dumps({"error": f"Yetersiz stok! Mevcut stok: {stock}, İstenen: {quantity}"}, ensure_ascii=False)

    total_price = price * quantity
    cursor.execute('''
        INSERT INTO orders (customer_name, comic_id, quantity, total_price)
        VALUES (?, ?, ?, ?)
    ''', (customer_name, comic_id, quantity, total_price))

    new_stock = stock - quantity
    cursor.execute('UPDATE comics SET stock = ? WHERE id = ?', (new_stock, comic_id))

    order_id = cursor.lastrowid
    conn.commit()
    conn.close()

    return json.dumps({
        "status": "Başarılı",
        "order_id": order_id,
        "customer_name": customer_name,
        "comic_title": title,
        "quantity": quantity,
        "total_price": f"{total_price} TL",
        "remaining_stock": new_stock
    }, ensure_ascii=False)

TOOL_MAP = {
    "get_comics_catalog": get_comics_catalog,
    "search_comic": search_comic,
    "create_order": create_order
}


# --- 4. MODEL VE AGENT MİMARİSİ ---
HF_TOKEN = os.environ.get("HF_TOKEN")

# Client'a api_key parametresini veriyoruz
client = InferenceClient(
    model="meta-llama/Llama-3.3-70B-Instruct",
    api_key=HF_TOKEN
)

def run_agent(user_message: str):
    messages = [
        {
            "role": "system",
            "content": (
                "Sen 'Çizgi Roman Diyarı' mağazasının müşteri asistanısın.\n"
                "ÖNEMLİ KURALLAR:\n"
                "1. Kullanıcı bir çizgi roman siparişi vermek istediğinde, ÖNCE 'search_comic' fonksiyonu ile o ürünün veritabanındaki ID'sini ve stok durumunu kontrol et.\n"
                "2. Eğer ürün stokta 0 ise veya bulunamadıysa asla sipariş oluşturma, kullanıcıya stokta olmadığını belirt.\n"
                "3. Eğer ürün var ve stok yeterliyse 'create_order' fonksiyonunu çağır.\n"
                "4. SADECE veritabanından dönen verileri kullan, uydurma bilgi verip halüsinasyon görme."
            )
        },
        {"role": "user", "content": user_message}
    ]

    max_turns = 3
    for _ in range(max_turns):
        response = client.chat_completion(
            messages=messages,
            tools=TOOLS_SCHEMA,
            tool_choice="auto",
            max_tokens=500
        )

        response_message = response.choices[0].message

        if response_message.tool_calls:
            messages.append(response_message)
            for tool_call in response_message.tool_calls:
                func_name = tool_call.function.name
                raw_args = tool_call.function.arguments
                func_args = json.loads(raw_args) if isinstance(raw_args, str) else raw_args

                if "comic_id" in func_args:
                    func_args["comic_id"] = int(func_args["comic_id"])
                if "quantity" in func_args:
                    func_args["quantity"] = int(func_args["quantity"])

                if func_name in TOOL_MAP:
                    tool_output = TOOL_MAP[func_name](**func_args)
                    messages.append({
                        "role": "tool",
                        "tool_call_id": tool_call.id,
                        "name": func_name,
                        "content": tool_output
                    })
        else:
            return response_message.content

    return "İşlem tamamlanamadı."

# --- 5. GRADIO ARAYÜZÜ ---
def chat_interface(message, history):
    return run_agent(message)

demo = gr.ChatInterface(
    fn=chat_interface,
    title=" Çizgi Roman Diyarı - Tool Calling Destekli Asistan",
    description="SQLite veritabanına bağlı yapay zeka asistanı. Stok kontrolü yapabilir, çizgi roman arayabilir ve sipariş oluşturabilir.",
    examples=[
        "Mağazadaki Marvel çizgi romanları nelerdir?",
        "Spider-Man: Blue çizgi romanından 2 adet sipariş vermek istiyorum. Adım Melda Kahraman.",
        "Akira Vol. 1 kitabından 1 adet sipariş vermek istiyorum. Adım Melda."
    ]
)

if __name__ == "__main__":
    demo.launch()