# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xO1-gTvT4e5TlsAKu4OFEaffG5TPUVtO
"""

import json
import os
import gradio as gr
from huggingface_hub import InferenceClient
import requests
import spaces  


HF_TOKEN = os.environ.get("HF_TOKEN")

MODEL_ID = "Qwen/Qwen2.5-72B-Instruct"

client = InferenceClient(model=MODEL_ID, token=HF_TOKEN)



# 2. API VE HESAPLAMA FONKSİYONLARI
def get_crypto_price(coin_id: str, vs_currency: str = "usd") -> dict:
    coin_id = str(coin_id).lower().strip()
    vs_currency = str(vs_currency).lower().strip()
    url = f"https://api.coingecko.com/api/v3/simple/price?ids={coin_id}&vs_currencies={vs_currency}"
    headers = {"User-Agent": "Mozilla/5.0"}
    try:
        res = requests.get(url, headers=headers, timeout=5).json()
        if coin_id in res and vs_currency in res[coin_id]:
            return {
                "coin_id": coin_id,
                "vs_currency": vs_currency,
                "price": float(res[coin_id][vs_currency]),
            }
        return {
            "error": f"'{coin_id}' coini veya '{vs_currency}' para birimi bulunamadı."
        }
    except Exception as e:
        return {"error": f"API Hatası: {str(e)}"}


def convert_currency(amount, from_code: str, to_code: str = "USD") -> dict:
    try:
        amount = float(amount)
    except Exception:
        return {"error": "Miktar geçerli bir sayı olmalıdır."}

    from_code = str(from_code).upper().strip()
    to_code = str(to_code).upper().strip()

    if from_code == to_code:
        return {
            "amount": amount,
            "from": from_code,
            "to": to_code,
            "result": amount,
        }

    url = f"https://api.frankfurter.app/latest?amount={amount}&from={from_code}&to={to_code}"
    try:
        res = requests.get(url, timeout=5).json()
        if "rates" in res and to_code in res["rates"]:
            return {
                "amount": amount,
                "from": from_code,
                "to": to_code,
                "result": float(res["rates"][to_code]),
            }
        return {
            "error": f"Döviz dönüşümü gerçekleştirilemedi ({from_code} -> {to_code})."
        }
    except Exception as e:
        return {"error": f"API Hatası: {str(e)}"}


def calculate_crypto_purchase(amount_fiat, price_per_coin) -> dict:
    try:
        amount_fiat = float(amount_fiat)
        price_per_coin = float(price_per_coin)
    except Exception:
        return {"error": "Parametreler geçerli bir sayı olmalıdır."}

    if price_per_coin <= 0:
        return {"error": "Coin fiyatı 0'dan büyük olmalıdır."}

    return {
        "amount_fiat": amount_fiat,
        "price_per_coin": price_per_coin,
        "crypto_purchased": round(amount_fiat / price_per_coin, 8),
    }


AVAILABLE_FUNCTIONS = {
    "get_crypto_price": get_crypto_price,
    "convert_currency": convert_currency,
    "calculate_crypto_purchase": calculate_crypto_purchase,
}


# 3. TOOL DEFINITIONS (JSON SCHEMA)
tools = [
    {
        "type": "function",
        "function": {
            "name": "get_crypto_price",
            "description": "Bir kripto paranın (bitcoin, ethereum, solana vb.) anlık fiyatını getirir.",
            "parameters": {
                "type": "object",
                "properties": {
                    "coin_id": {"type": "string", "description": "Coin ID'si"},
                    "vs_currency": {
                        "type": "string",
                        "description": "Para birimi (usd, try, eur)",
                    },
                },
                "required": ["coin_id"],
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": "convert_currency",
            "description": "İki reel para birimi (TRY, USD, EUR) arasında dönüşüm yapar.",
            "parameters": {
                "type": "object",
                "properties": {
                    "amount": {
                        "type": "number",
                        "description": "Dönüştürülecek miktar",
                    },
                    "from_code": {
                        "type": "string",
                        "description": "Kaynak para birimi",
                    },
                    "to_code": {
                        "type": "string",
                        "description": "Hedef para birimi",
                    },
                },
                "required": ["amount", "from_code", "to_code"],
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": "calculate_crypto_purchase",
            "description": "Fiat para ve coin fiyatına göre kaç adet coin alınacağını hesaplar.",
            "parameters": {
                "type": "object",
                "properties": {
                    "amount_fiat": {
                        "type": "number",
                        "description": "Toplam para miktarı",
                    },
                    "price_per_coin": {
                        "type": "number",
                        "description": "1 coinin fiyatı",
                    },
                },
                "required": ["amount_fiat", "price_per_coin"],
            },
        },
    },
]



# 4.PREDICT FONKSİYONU
@spaces.GPU 
def predict(message, history):
    system_prompt = (
        "Sen yardımcı bir Finans Asistanısın. Sadece Türkçe yanıt ver.\n"
        "Kurallar:\n"
        "1. Kullanıcı paranın başka para birimindeki karşılığını sorduğunda 'convert_currency' kullan.\n"
        "2. Kripto para fiyatı için 'get_crypto_price' kullan.\n"
        "3. Alınacak kripto miktarını hesaplamak için 'calculate_crypto_purchase' kullan.\n"
        "4. Asla kafandan rakam sallama veya Türkçe dışı diller kullanma."
    )

    messages = [{"role": "system", "content": system_prompt}]

    if history:
        for item in history:
            if isinstance(item, (list, tuple)):
                if item[0]:
                    messages.append({"role": "user", "content": str(item[0])})
                if item[1]:
                    messages.append(
                        {"role": "assistant", "content": str(item[1])}
                    )
            elif isinstance(item, dict):
                messages.append(
                    {"role": item.get("role"), "content": item.get("content")}
                )

    messages.append({"role": "user", "content": message})

    trace_logs = []
    turn_counter = 1

    while turn_counter <= 5:
        try:
            response = client.chat.completions.create(
                model=MODEL_ID,
                messages=messages,
                tools=tools,
                tool_choice="auto",
                max_tokens=1000,
            )
        except Exception as e:
            return f"Model Bağlantı Hatası: {str(e)}"

        response_message = response.choices[0].message

        if response_message.tool_calls:
            messages.append(response_message)
            trace_logs.append(f"###  [Turn {turn_counter}] Araç Çağrıları:")

            for tool_call in response_message.tool_calls:
                func_name = tool_call.function.name
                func_args = json.loads(tool_call.function.arguments)

                trace_logs.append(f"  -> **{func_name}**({func_args})")

                if func_name in AVAILABLE_FUNCTIONS:
                    function_response = AVAILABLE_FUNCTIONS[func_name](
                        **func_args
                    )
                else:
                    function_response = {
                        "error": f"Tanımsız fonksiyon: {func_name}"
                    }

                trace_logs.append(f"  <- `{function_response}`")

                messages.append(
                    {
                        "tool_call_id": tool_call.id,
                        "role": "tool",
                        "name": func_name,
                        "content": json.dumps(function_response),
                    }
                )

            trace_logs.append("")
            turn_counter += 1
        else:
            final_reply = response_message.content
            formatted_logs = "\n".join(trace_logs)

            full_response = ""
            if formatted_logs:
                full_response += (
                    f"###  Arka Plan İşlem Adımları (Trace Log)\n\n"
                    f"{formatted_logs}\n---\n"
                )

            full_response += f"###  Yanıt:\n{final_reply}"
            return full_response

    return "Maksimum adım sayısına ulaşıldı."


# 5. GRADIO ARAYÜZÜ
demo = gr.ChatInterface(
    fn=predict,
    title=" Kripto & Döviz Portföy Asistanı (Tool Calling Demo)",
    description="Bu asistan arka planda CoinGecko ve Frankfurter API araçlarını çağırarak adımları şeffafça gösterir.",
)

if __name__ == "__main__":
    demo.launch()